---
- hosts: nginx
  become: true
  tasks:
    - name: install nginx
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - nginx
        - curl
    - name: start nginx
      service: name=nginx state=started enabled=true

- hosts: db
  become: true
  tasks:
      - name: install postgres
        apt: name={{item}} state=latest update_cache=yes
        with_items:
          - postgresql
          - curl
      - name: start postgres
        service: name=postgresql state=started enabled=true

- hosts: web
  become: true
  tasks:
      - name: install python pip
        apt: name={{item}} state=latest update_cache=yes
        with_items:
            - python3
            - python-pip
            - curl


# Tasks consist in Ansible of:
# - Module
# - Arguments for the Module
